baseURL = "https://civcubed.net/"
languageCode = "en"
title = "CivCubed"
theme = "cc"
paginate = 6
DefaultContentLanguage = "en"

[markup.goldmark.renderer]
    unsafe = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[params]
    description = "Collaborative worldbuilding project in Minecraft to build diverse societies with different laws, cultures, and more!"

[languages]
    [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1

[security]
	[security.exec]
		allow = ['^go$', '^npx$', '^postcss$', '^babel$']
